/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Livoice AI Transcript Chat API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { axiosClient } from "./axiosClient";
export interface CreateTranscriptRequest {
  /** @minLength 1 */
  title: string;
  description?: string;
  intervieweeName?: string;
  transcriptDate: string;
  text?: string;
}

export type UploadTextRequestTimelineItem = {
  absoluteTimestamp: number;
  durationSeconds?: number;
  speaker?: string;
};

export interface UploadTextRequest {
  /** @minLength 1 */
  text: string;
  timeline?: UploadTextRequestTimelineItem[];
}

export interface ChatRequest {
  /** @minLength 1 */
  userMessage: string;
  sessionId?: string;
}

export type TranscriptSummaryDescription = string | null;

export type TranscriptSummaryIntervieweeName = string | null;

export interface TranscriptSummary {
  id: string;
  title: string;
  description: TranscriptSummaryDescription;
  intervieweeName: TranscriptSummaryIntervieweeName;
  transcriptDate: string;
  createdAt: string;
  updatedAt: string;
  chunkCount: number;
}

export type TranscriptDetailDescription = string | null;

export type TranscriptDetailIntervieweeName = string | null;

export interface TranscriptDetail {
  id: string;
  title: string;
  description: TranscriptDetailDescription;
  intervieweeName: TranscriptDetailIntervieweeName;
  transcriptDate: string;
  createdAt: string;
  updatedAt: string;
  chunkCount: number;
  textPreview: string;
}

export type TranscriptChunkSpeaker = string | null;

export type TranscriptChunkAbsoluteTimestamp = number | null;

export type TranscriptChunkDurationSeconds = number | null;

export interface TranscriptChunk {
  id: string;
  speaker: TranscriptChunkSpeaker;
  text: string;
  absoluteTimestamp: TranscriptChunkAbsoluteTimestamp;
  durationSeconds: TranscriptChunkDurationSeconds;
}

export type ChatResponseUsedChunksItemSpeaker = string | null;

export type ChatResponseUsedChunksItemAbsoluteTimestamp = number | null;

export type ChatResponseUsedChunksItemDurationSeconds = number | null;

export type ChatResponseUsedChunksItem = {
  id: string;
  speaker: ChatResponseUsedChunksItemSpeaker;
  text: string;
  absoluteTimestamp: ChatResponseUsedChunksItemAbsoluteTimestamp;
  durationSeconds: ChatResponseUsedChunksItemDurationSeconds;
};

export interface ChatResponse {
  sessionId: string;
  answer: string;
  usedChunks: ChatResponseUsedChunksItem[];
}

export interface UploadTextResponse {
  chunksCreated: number;
}

export type GetTranscripts200ItemDescription = string | null;

export type GetTranscripts200ItemIntervieweeName = string | null;

export type GetTranscripts200Item = {
  id: string;
  title: string;
  description: GetTranscripts200ItemDescription;
  intervieweeName: GetTranscripts200ItemIntervieweeName;
  transcriptDate: string;
  createdAt: string;
  updatedAt: string;
  chunkCount: number;
};

export type PostTranscriptsBody = {
  /** @minLength 1 */
  title: string;
  description?: string;
  intervieweeName?: string;
  transcriptDate: string;
  text?: string;
};

export type PostTranscripts201Description = string | null;

export type PostTranscripts201IntervieweeName = string | null;

export type PostTranscripts201 = {
  id: string;
  title: string;
  description: PostTranscripts201Description;
  intervieweeName: PostTranscripts201IntervieweeName;
  transcriptDate: string;
  createdAt: string;
  updatedAt: string;
  chunkCount: number;
};

export type GetTranscriptsId200Description = string | null;

export type GetTranscriptsId200IntervieweeName = string | null;

export type GetTranscriptsId200 = {
  id: string;
  title: string;
  description: GetTranscriptsId200Description;
  intervieweeName: GetTranscriptsId200IntervieweeName;
  transcriptDate: string;
  createdAt: string;
  updatedAt: string;
  chunkCount: number;
  textPreview: string;
};

export type PostTranscriptsIdUploadTextBodyTimelineItem = {
  absoluteTimestamp: number;
  durationSeconds?: number;
  speaker?: string;
};

export type PostTranscriptsIdUploadTextBody = {
  /** @minLength 1 */
  text: string;
  timeline?: PostTranscriptsIdUploadTextBodyTimelineItem[];
};

export type PostTranscriptsIdUploadText200 = {
  chunksCreated: number;
};

export type GetTranscriptsIdChunks200ItemSpeaker = string | null;

export type GetTranscriptsIdChunks200ItemAbsoluteTimestamp = number | null;

export type GetTranscriptsIdChunks200ItemDurationSeconds = number | null;

export type GetTranscriptsIdChunks200Item = {
  id: string;
  speaker: GetTranscriptsIdChunks200ItemSpeaker;
  text: string;
  absoluteTimestamp: GetTranscriptsIdChunks200ItemAbsoluteTimestamp;
  durationSeconds: GetTranscriptsIdChunks200ItemDurationSeconds;
};

export type PostTranscriptsIdChatBody = {
  /** @minLength 1 */
  userMessage: string;
  sessionId?: string;
};

export type PostTranscriptsIdChat200UsedChunksItemSpeaker = string | null;

export type PostTranscriptsIdChat200UsedChunksItemAbsoluteTimestamp =
  | number
  | null;

export type PostTranscriptsIdChat200UsedChunksItemDurationSeconds =
  | number
  | null;

export type PostTranscriptsIdChat200UsedChunksItem = {
  id: string;
  speaker: PostTranscriptsIdChat200UsedChunksItemSpeaker;
  text: string;
  absoluteTimestamp: PostTranscriptsIdChat200UsedChunksItemAbsoluteTimestamp;
  durationSeconds: PostTranscriptsIdChat200UsedChunksItemDurationSeconds;
};

export type PostTranscriptsIdChat200 = {
  sessionId: string;
  answer: string;
  usedChunks: PostTranscriptsIdChat200UsedChunksItem[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List transcripts
 */
export const getTranscripts = (
  options?: SecondParameter<typeof axiosClient>,
  signal?: AbortSignal,
) => {
  return axiosClient<GetTranscripts200Item[]>(
    { url: `/transcripts`, method: "GET", signal },
    options,
  );
};

export const getGetTranscriptsQueryKey = () => {
  return [`/transcripts`] as const;
};

export const getGetTranscriptsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTranscripts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getTranscripts>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTranscriptsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTranscripts>>> = ({
    signal,
  }) => getTranscripts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTranscripts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTranscriptsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTranscripts>>
>;
export type GetTranscriptsQueryError = unknown;

export function useGetTranscripts<
  TData = Awaited<ReturnType<typeof getTranscripts>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTranscripts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscripts>>,
          TError,
          Awaited<ReturnType<typeof getTranscripts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTranscripts<
  TData = Awaited<ReturnType<typeof getTranscripts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTranscripts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscripts>>,
          TError,
          Awaited<ReturnType<typeof getTranscripts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTranscripts<
  TData = Awaited<ReturnType<typeof getTranscripts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTranscripts>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List transcripts
 */

export function useGetTranscripts<
  TData = Awaited<ReturnType<typeof getTranscripts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTranscripts>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTranscriptsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a transcript and optionally ingest text
 */
export const postTranscripts = (
  postTranscriptsBody: PostTranscriptsBody,
  options?: SecondParameter<typeof axiosClient>,
  signal?: AbortSignal,
) => {
  return axiosClient<PostTranscripts201>(
    {
      url: `/transcripts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTranscriptsBody,
      signal,
    },
    options,
  );
};

export const getPostTranscriptsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTranscripts>>,
    TError,
    { data: PostTranscriptsBody },
    TContext
  >;
  request?: SecondParameter<typeof axiosClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTranscripts>>,
  TError,
  { data: PostTranscriptsBody },
  TContext
> => {
  const mutationKey = ["postTranscripts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTranscripts>>,
    { data: PostTranscriptsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postTranscripts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTranscriptsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTranscripts>>
>;
export type PostTranscriptsMutationBody = PostTranscriptsBody;
export type PostTranscriptsMutationError = unknown;

/**
 * @summary Create a transcript and optionally ingest text
 */
export const usePostTranscripts = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTranscripts>>,
      TError,
      { data: PostTranscriptsBody },
      TContext
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTranscripts>>,
  TError,
  { data: PostTranscriptsBody },
  TContext
> => {
  const mutationOptions = getPostTranscriptsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Fetch transcript
 */
export const getTranscriptsId = (
  id: string,
  options?: SecondParameter<typeof axiosClient>,
  signal?: AbortSignal,
) => {
  return axiosClient<GetTranscriptsId200>(
    { url: `/transcripts/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetTranscriptsIdQueryKey = (id?: string) => {
  return [`/transcripts/${id}`] as const;
};

export const getGetTranscriptsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTranscriptsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTranscriptsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTranscriptsId>>
  > = ({ signal }) => getTranscriptsId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTranscriptsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTranscriptsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTranscriptsId>>
>;
export type GetTranscriptsIdQueryError = void;

export function useGetTranscriptsId<
  TData = Awaited<ReturnType<typeof getTranscriptsId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscriptsId>>,
          TError,
          Awaited<ReturnType<typeof getTranscriptsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTranscriptsId<
  TData = Awaited<ReturnType<typeof getTranscriptsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscriptsId>>,
          TError,
          Awaited<ReturnType<typeof getTranscriptsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTranscriptsId<
  TData = Awaited<ReturnType<typeof getTranscriptsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Fetch transcript
 */

export function useGetTranscriptsId<
  TData = Awaited<ReturnType<typeof getTranscriptsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTranscriptsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Add transcript text
 */
export const postTranscriptsIdUploadText = (
  id: string,
  postTranscriptsIdUploadTextBody: PostTranscriptsIdUploadTextBody,
  options?: SecondParameter<typeof axiosClient>,
  signal?: AbortSignal,
) => {
  return axiosClient<PostTranscriptsIdUploadText200>(
    {
      url: `/transcripts/${id}/upload-text`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTranscriptsIdUploadTextBody,
      signal,
    },
    options,
  );
};

export const getPostTranscriptsIdUploadTextMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTranscriptsIdUploadText>>,
    TError,
    { id: string; data: PostTranscriptsIdUploadTextBody },
    TContext
  >;
  request?: SecondParameter<typeof axiosClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTranscriptsIdUploadText>>,
  TError,
  { id: string; data: PostTranscriptsIdUploadTextBody },
  TContext
> => {
  const mutationKey = ["postTranscriptsIdUploadText"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTranscriptsIdUploadText>>,
    { id: string; data: PostTranscriptsIdUploadTextBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return postTranscriptsIdUploadText(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTranscriptsIdUploadTextMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTranscriptsIdUploadText>>
>;
export type PostTranscriptsIdUploadTextMutationBody =
  PostTranscriptsIdUploadTextBody;
export type PostTranscriptsIdUploadTextMutationError = unknown;

/**
 * @summary Add transcript text
 */
export const usePostTranscriptsIdUploadText = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTranscriptsIdUploadText>>,
      TError,
      { id: string; data: PostTranscriptsIdUploadTextBody },
      TContext
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTranscriptsIdUploadText>>,
  TError,
  { id: string; data: PostTranscriptsIdUploadTextBody },
  TContext
> => {
  const mutationOptions =
    getPostTranscriptsIdUploadTextMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary List transcript chunks
 */
export const getTranscriptsIdChunks = (
  id: string,
  options?: SecondParameter<typeof axiosClient>,
  signal?: AbortSignal,
) => {
  return axiosClient<GetTranscriptsIdChunks200Item[]>(
    { url: `/transcripts/${id}/chunks`, method: "GET", signal },
    options,
  );
};

export const getGetTranscriptsIdChunksQueryKey = (id?: string) => {
  return [`/transcripts/${id}/chunks`] as const;
};

export const getGetTranscriptsIdChunksQueryOptions = <
  TData = Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTranscriptsIdChunksQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTranscriptsIdChunks>>
  > = ({ signal }) => getTranscriptsIdChunks(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTranscriptsIdChunksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTranscriptsIdChunks>>
>;
export type GetTranscriptsIdChunksQueryError = unknown;

export function useGetTranscriptsIdChunks<
  TData = Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
          TError,
          Awaited<ReturnType<typeof getTranscriptsIdChunks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTranscriptsIdChunks<
  TData = Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
          TError,
          Awaited<ReturnType<typeof getTranscriptsIdChunks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTranscriptsIdChunks<
  TData = Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List transcript chunks
 */

export function useGetTranscriptsIdChunks<
  TData = Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTranscriptsIdChunks>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTranscriptsIdChunksQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Ask a question about a transcript
 */
export const postTranscriptsIdChat = (
  id: string,
  postTranscriptsIdChatBody: PostTranscriptsIdChatBody,
  options?: SecondParameter<typeof axiosClient>,
  signal?: AbortSignal,
) => {
  return axiosClient<PostTranscriptsIdChat200>(
    {
      url: `/transcripts/${id}/chat`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postTranscriptsIdChatBody,
      signal,
    },
    options,
  );
};

export const getPostTranscriptsIdChatMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTranscriptsIdChat>>,
    TError,
    { id: string; data: PostTranscriptsIdChatBody },
    TContext
  >;
  request?: SecondParameter<typeof axiosClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTranscriptsIdChat>>,
  TError,
  { id: string; data: PostTranscriptsIdChatBody },
  TContext
> => {
  const mutationKey = ["postTranscriptsIdChat"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTranscriptsIdChat>>,
    { id: string; data: PostTranscriptsIdChatBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return postTranscriptsIdChat(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTranscriptsIdChatMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTranscriptsIdChat>>
>;
export type PostTranscriptsIdChatMutationBody = PostTranscriptsIdChatBody;
export type PostTranscriptsIdChatMutationError = unknown;

/**
 * @summary Ask a question about a transcript
 */
export const usePostTranscriptsIdChat = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTranscriptsIdChat>>,
      TError,
      { id: string; data: PostTranscriptsIdChatBody },
      TContext
    >;
    request?: SecondParameter<typeof axiosClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTranscriptsIdChat>>,
  TError,
  { id: string; data: PostTranscriptsIdChatBody },
  TContext
> => {
  const mutationOptions = getPostTranscriptsIdChatMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
